name = "std::blueprint::default"
version = "1.0.2"
description = "Project blueprint for a basic website"
repository = "https://github.com/uwe-app/blueprints"
type = "site"
keywords = ["Project", "Blueprint"]
license = ["MIT", "Apache-2.0"]
