name = "std::blueprint::deck"
version = "1.1.1"
description = "Project blueprint for a deck"
repository = "https://github.com/uwe-app/blueprints"
type = "blueprint"
keywords = ["Project", "Blueprint"]
license = ["MIT", "Apache-2.0"]

[compute]
assets = false
styles = false
scripts = false
fonts = false
plugins = false
partials = false
layouts = false

[blueprint.files]
excludes = ["test/**"]
