lang = "en"
host = "localhost"

[dependencies."std::core"]
version = "^5"
apply = { styles = ["**"] }

[dependencies."std::menu"]
version = "^1.0.2"
#apply = { styles = ["**"] }

[dependencies."lib::reveal"]
version = "^1"
apply = { styles = ["/"], scripts = ["/"] }

[dependencies."std::syntax"]
version = "^1"

[dependencies."std::sidebar"]
version = "~1"
apply = { scripts = [ "**" ] }

[page.meta]
description = "Deck"
keywords = "Presentation, Deck"

[menu.slides]
pages = [
  "/welcome/",
  "/slides/",
  "/create-file/",
  "/create-menu-item/",
  "/remove-file/",
  "/remove-menu-item/",
  "/reset/",
  "/finish/",
]

[syntax]
theme = "Solarized (light)"

