name = "std::blueprint::blog"
version = "1.0.1"
description = "Project blueprint for a blog"
repository = "https://github.com/uwe-app/blueprints"
type = "blueprint"
keywords = ["Project", "Blueprint"]
license = ["MIT", "Apache-2.0"]

[compute]
assets = false
styles = false
scripts = false
fonts = false
plugins = false

[blueprint.files]
includes = ["site/partials/header.hbs", "site/partials/footer.hbs"]
excludes = ["site/partials/*.hbs"]
