name = "std::blueprint::blog"
version = "1.0.0"
description = "Project blueprint for a blog"
repository = "https://github.com/uwe-app/blueprints"
type = "blueprint"
keywords = ["Project", "Blueprint"]
license = ["MIT", "Apache-2.0"]
